version: '3'
services:
#Registry
  registry:
    image: registry:2.7
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry-config/credentials.yml:/etc/docker/registry/config.yml
      - ./registry-config/htpasswd:/etc/docker/registry/htpasswd
    networks:
      - docker-registry
  #Registry UI
  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - "5001:80"
    environment:
      - REGISTRY_TITLE=Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      - docker-registry
#Docker Networks
networks:
  docker-registry:
    driver: bridge
#Volumes
volumes:
  registrydata:
    driver: local