version: '3'
services:
    registry:
        image: registry:2
        volumes:
        - "/tmp/docker_registry:/var/lib/registry"
        ports:
        - 5000:5000
        networks:
        - docker-registry
        restart: always
    ui:
      image: joxit/docker-registry-ui:latest
      ports:
        - "5001:80"
      environment:
        - REGISTRY_TITLE=My Private Docker Registry
        - REGISTRY_URL=http://registry:5000
      depends_on:
        - registry
      networks:
        - docker-registry
networks:
  docker-registry
